package laboratorio1_trabajo;

public enum Tokens {
	 TOK_MAIN,             
	 TOK_INT,                
	 TOK_BOOLEAN,          
	 TOK_IF,                 
	 TOK_ELSE,            
	 TOK_WHILE,              
	 TOK_SCANF,              
	 TOK_PRINTF,             
	 TOK_PUNTOYCOMA,        
	 TOK_COMA,               
	 TOK_PARENTESISIZQUIERDO,
	 TOK_PARENTESISDERECHO,  
	 TOK_LLAVEIZQUIERDA,     
	 TOK_LLAVEDERECHA,       
	 TOK_ASIGNACION,         
	 TOK_MAS,                
	 TOK_MENOS,              
	 TOK_DIVISION,          
	 TOK_ASTERISCO,          
	 TOK_AND,                
	 TOK_OR,                 
	 TOK_NOT,                
	 TOK_IGUAL,              
	 TOK_DISTINTO,           
	 TOK_MENORIGUAL,         
	 TOK_MAYORIGUAL,         
	 TOK_MENOR,              
	 TOK_MAYOR,              
	 TOK_IDENTIFICADOR,      
	 TOK_CONSTANTE_ENTERA,   
	 TOK_TRUE,               
	 TOK_FALSE,   
	 TOK_NUMERO,
	 TOK_ERROR
	}