
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package calculadora;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TOK_MENOS = 3;
  public static final int TOK_PARD = 7;
  public static final int TOK_ERROR = 9;
  public static final int TOK_DIVISION = 5;
  public static final int TOK_CONSTANTE = 8;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int TOK_PRODUCTO = 4;
  public static final int TOK_MAS = 2;
  public static final int MENOSU = 10;
  public static final int TOK_PARI = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TOK_MAS",
  "TOK_MENOS",
  "TOK_PRODUCTO",
  "TOK_DIVISION",
  "TOK_PARI",
  "TOK_PARD",
  "TOK_CONSTANTE",
  "TOK_ERROR",
  "MENOSU"
  };
}

